exercism/cairo

.github/workflows/test.yml
bin/format_exercises.sh
bin/lint_markdown.sh
bin/verify-exercises
config.json
docs/ABOUT.md
exercises/practice/armstrong-numbers/.docs/instructions.md
exercises/practice/leap/.docs/introduction.md
exercises/practice/lucians-luscious-lasagna/.docs/hints.md
exercises/practice/lucians-luscious-lasagna/.docs/instructions.md
exercises/practice/lucians-luscious-lasagna/.docs/introduction.md
exercises/practice/lucians-luscious-lasagna/.meta/config.json
exercises/practice/lucians-luscious-lasagna/.meta/design.md
exercises/practice/lucians-luscious-lasagna/.meta/example.cairo
exercises/practice/lucians-luscious-lasagna/Scarb.toml
exercises/practice/lucians-luscious-lasagna/src/lib.cairo
exercises/practice/lucians-luscious-lasagna/src/tests.cairo
exercises/practice/semi-structured-logs/.docs/hints.md

Add Lucians luscious lasagna exercise

---

exercises/practice/armstrong-numbers/.meta/example.cairo
exercises/practice/armstrong-numbers/src/lib.cairo
exercises/practice/armstrong-numbers/src/tests.cairo
exercises/practice/beer-song/src/tests.cairo

Test alignment

---

config.json
exercises/practice/anagram/.docs/instructions.md
exercises/practice/anagram/.docs/introduction.md
exercises/practice/anagram/.meta/config.json
exercises/practice/anagram/.meta/example.cairo
exercises/practice/anagram/.meta/tests.toml
exercises/practice/anagram/Scarb.toml
exercises/practice/anagram/src/lib.cairo
exercises/practice/anagram/src/tests.cairo

Close #22 
Also includes the following change: **add complex-numbers to foregone**.
Reason: Cairo does not support floating point numbers.

Add "Anagram" exercise

---

config.json

Closes #75, Closes #82
@ErikSchierboom @iHiD wasn't sure what does the launch process look exactly, so created this PR for you to approve once it _should_ be launched. Please let me know if I should contact somebody else regarding this.
I created a request to add Cairo logos, but they have not yet been added:
https://github.com/exercism/website-icons/issues/176
Does this preclude launching or can we launch regardless?

Set track to active

---

exercises/concept/low-power-embedded-game/.meta/config.json

```
(base) ➜  exercism-cairo git:(main) ./bin/configlet sync
Updating cached 'problem-specifications' data...
Checking exercises...
[warn] filepaths: unsynced: low-power-embedded-game
[warn] some exercises have unsynced filepaths
```
Configlet is complaining this concept exercise is missing an invalidator entry. The other exercises all seem to have it so I'm adding so configlet won't complain about it.

Add missing invalidator to `low-power-embedded-game`

---

config.json
exercises/practice/collatz-conjecture/.docs/instructions.md
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/collatz-conjecture/.meta/example.cairo
exercises/practice/collatz-conjecture/.meta/tests.toml
exercises/practice/collatz-conjecture/Scarb.toml
exercises/practice/collatz-conjecture/src/lib.cairo
exercises/practice/collatz-conjecture/tests/collatz_conjecture.cairo

For #48in24.
Towards #113 
`configlet create --practice-exercise <slug>` formats the track config so that's why the practices array for reverse string was edited. I used unsigned ints so the tests for zero or a negative number were skipped.

Add collatz-conjecture

---

bin/lint_markdown.sh

Makes little sense to lint autogenerated files - if Exercism deems the file well formatted, who are we to judge.
Prompted to update this by https://github.com/exercism/cairo/pull/141#issuecomment-2323203160

Stop linting autogenerated exercise .md files

---

config.json

- [react](https://github.com/exercism/problem-specifications/tree/main/exercises/react): Cairo does not currently support passing callback functions to other functions
- [paasio](https://github.com/exercism/problem-specifications/tree/main/exercises/paasio): Cairo does not support accessing file and/or network data
- [lens-person](https://github.com/exercism/problem-specifications/tree/main/exercises/lens-person): Since callback functions are not supported, there's currently no way to implement lenses in Cairo

Expand foregone exercises array

---

config.json
exercises/practice/resistor-color-duo/.docs/instructions.md
exercises/practice/resistor-color-duo/.meta/config.json
exercises/practice/resistor-color-duo/.meta/example.cairo
exercises/practice/resistor-color-duo/.meta/tests.toml
exercises/practice/resistor-color-duo/Scarb.toml
exercises/practice/resistor-color-duo/src/lib.cairo
exercises/practice/resistor-color-duo/tests/resistor_color_duo.cairo

Towards #223
I used an enum here so `resistor-color` and `resistor-color-trio` should also use similar enums for consistency. The intention is that a student works through these three exercises as a group, unlocking more complexity along the way.
Some tracks omit the test about ignoring additional colors. Exercism as a whole doesn't make a big deal of input validation except for a few specific exercises.  If we choose to not include the test, then we can use two Color parameters instead of the array.

Add resistor-color-duo

---

config.json
exercises/practice/atbash-cipher/.docs/instructions.md
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/atbash-cipher/.meta/example.cairo
exercises/practice/atbash-cipher/.meta/tests.toml
exercises/practice/atbash-cipher/Scarb.toml
exercises/practice/atbash-cipher/src/lib.cairo
exercises/practice/atbash-cipher/tests/atbash_cipher.cairo

Add atbash-cipher

---

bin/verify-exercises

Addresses https://github.com/exercism/cairo/pull/274#issuecomment-2346764805

Fix: call 'exit 1' only if test times out (fix command precedence)

---

exercises/practice/protein-translation/.meta/example.cairo
exercises/practice/protein-translation/src/lib.cairo
exercises/practice/protein-translation/tests/protein_translation.cairo

Closes #https://github.com/exercism/cairo/issues/109

Sync `protein-translation` with Canonical Data

---

config.json
exercises/practice/kindergarten-garden/.docs/instructions.md
exercises/practice/kindergarten-garden/.docs/introduction.md
exercises/practice/kindergarten-garden/.meta/config.json
exercises/practice/kindergarten-garden/.meta/example.cairo
exercises/practice/kindergarten-garden/.meta/tests.toml
exercises/practice/kindergarten-garden/Scarb.toml
exercises/practice/kindergarten-garden/src/lib.cairo
exercises/practice/kindergarten-garden/tests/kindergarten_garden.cairo

Add `kindergarten-garden` exercise

---

config.json
exercises/practice/zipper/.docs/instructions.md
exercises/practice/zipper/.meta/config.json
exercises/practice/zipper/.meta/example.cairo
exercises/practice/zipper/.meta/tests.toml
exercises/practice/zipper/Scarb.toml
exercises/practice/zipper/src/lib.cairo
exercises/practice/zipper/tests/zipper.cairo

Add Zipper

---

config.json
exercises/practice/binary-search-tree/.docs/instructions.append.md
exercises/practice/binary-search-tree/.docs/instructions.md
exercises/practice/binary-search-tree/.meta/config.json
exercises/practice/binary-search-tree/.meta/example.cairo
exercises/practice/binary-search-tree/.meta/tests.toml
exercises/practice/binary-search-tree/Scarb.toml
exercises/practice/binary-search-tree/src/lib.cairo
exercises/practice/binary-search-tree/tests/binary_search_tree.cairo

Binary search tree

---

config.json

Closes #188 
Cairo was not built to work with files.

feat: add `grep` to foregone exercises

---

bin/verify-exercises

Avoids issues like this https://github.com/exercism/cairo/pull/304#discussion_r1838181207

Add `scarb build` step to check lib.cairo during verify-exercise

---

concepts/error-handling/about.md
concepts/error-handling/links.json
config.json
exercises/concept/calculator-conundrum/.docs/hints.md
exercises/concept/calculator-conundrum/.docs/instructions.md
exercises/concept/calculator-conundrum/.docs/introduction.md
exercises/concept/calculator-conundrum/.meta/config.json
exercises/concept/calculator-conundrum/.meta/design.md
exercises/concept/calculator-conundrum/.meta/exemplar.cairo
exercises/concept/calculator-conundrum/Scarb.toml
exercises/concept/calculator-conundrum/src/lib.cairo
exercises/concept/calculator-conundrum/tests/calculator_conundrum.cairo
single-sentence-per-line-rule.js

add Calculator conundrum concept exercise

---

concepts/functions/.meta/config.json
concepts/functions/about.md
concepts/functions/introduction.md
concepts/functions/links.json

Functions concept

---

exercises/concept/the-realm-of-echoes/.docs/hints.md
exercises/concept/the-realm-of-echoes/.docs/introduction.md
exercises/concept/the-realm-of-echoes/.meta/config.json
exercises/concept/the-realm-of-echoes/.meta/design.md
exercises/concept/the-realm-of-echoes/tests/the_realm_of_echoes.cairo

Closes #271 
Related https://github.com/exercism/cairo/pull/323

Add Concept Exercise Metadata files: `the-realm-of-echoes`

---

concepts/control-flow/.meta/config.json
concepts/control-flow/links.json
concepts/smart-pointers/.meta/config.json
concepts/smart-pointers/about.md
concepts/smart-pointers/introduction.md
concepts/smart-pointers/links.json

Closes #59 
Related https://github.com/exercism/cairo/pull/322

Write the "Smart Pointers" concept

---

concepts/associated-items/.meta/config.json
concepts/associated-items/about.md
concepts/associated-items/introduction.md
concepts/associated-items/links.json
config.json

implement associated items concept

---

concepts/method-syntax/.meta/config.json
concepts/method-syntax/about.md
concepts/method-syntax/introduction.md
concepts/method-syntax/links.json

implement method syntax concept

---

concepts/arrays/links.json
exercises/concept/magician-in-training/.docs/hints.md
exercises/concept/magician-in-training/.docs/instructions.append.md
exercises/concept/magician-in-training/.docs/instructions.md
exercises/concept/magician-in-training/.docs/introduction.md
exercises/concept/magician-in-training/.meta/config.json
exercises/concept/magician-in-training/.meta/design.md
exercises/concept/magician-in-training/.meta/exemplar.cairo
exercises/concept/magician-in-training/Scarb.toml
exercises/concept/magician-in-training/src/lib.cairo
exercises/concept/magician-in-training/tests/magician_in_training.cairo

Add magician-in-training

---

bin/verify-exercises

Exercism actually [expects this `custom` field to be a JSON object](https://exercism.org/docs/building/tracks/concept-exercises#h-file-meta-config-json), otherwise running `./bin/configlet fmt -uy` removes the field.
Also, updated the custom field to a more meaningful name.

Update verify-exercise to process valid Exercism 'custom' field

---

config.json
exercises/concept/cars-assemble/.meta/config.json

Towards #377 
This reverts commit 1f449ce3c872cc6a114dd52105db89cddfa03a8f.
Based on this discussion:
https://forum.exercism.org/t/long-removed-learning-exercise-appears-in-concept/18773
Following this guide:
https://exercism.org/docs/building/tracks/deprecated-exercises#h-deprecating-an-exercise

Add back `cars-assemble` (PR #341) and mark "deprecated"
