exercism/cairo

docs/ABOUT.md

For some reason GitHub felt I needed to know about this repo. Then I land in it, enthusiastic about Cairo the graphics library, and it pointed me at this dWeb nonsense technology.
This hopefully helps others.

docs: Add basic information about Cairo

---

bin/verify-exercises
config.json
exercises/practice/allergies/.docs/instructions.md
exercises/practice/allergies/.meta/config.json
exercises/practice/allergies/.meta/example.cairo
exercises/practice/allergies/.meta/tests.toml
exercises/practice/allergies/Scarb.toml
exercises/practice/allergies/src/lib.cairo
exercises/practice/allergies/src/tests.cairo

Add allergies exercise

---

concepts/felts/.meta/config.json
concepts/felts/about.md
concepts/felts/introduction.md

- Felt type ```Introduction.md``` updated
- Felt type  ```about.md``` updated

Felt type introduction added

---

config.json
exercises/practice/rational-numbers/.docs/instructions.md
exercises/practice/rational-numbers/.meta/config.json
exercises/practice/rational-numbers/.meta/example.cairo
exercises/practice/rational-numbers/.meta/tests.toml
exercises/practice/rational-numbers/Scarb.toml
exercises/practice/rational-numbers/src/lib.cairo
exercises/practice/rational-numbers/src/tests.cairo

Add rational-numbers exercise

---

config.json
exercises/practice/scrabble-score/.docs/instructions.md
exercises/practice/scrabble-score/.docs/introduction.md
exercises/practice/scrabble-score/.meta/config.json
exercises/practice/scrabble-score/.meta/example.cairo
exercises/practice/scrabble-score/.meta/tests.toml
exercises/practice/scrabble-score/Scarb.toml
exercises/practice/scrabble-score/src/lib.cairo
exercises/practice/scrabble-score/src/tests.cairo

Add scrabble-score exercise

---

config.json
exercises/practice/dominoes/.docs/instructions.md
exercises/practice/dominoes/.meta/config.json
exercises/practice/dominoes/.meta/example.cairo
exercises/practice/dominoes/.meta/tests.toml
exercises/practice/dominoes/Scarb.toml
exercises/practice/dominoes/src/lib.cairo
exercises/practice/dominoes/src/tests.cairo

Add dominoes exercise

---

concepts/strings/.meta/config.json
concepts/strings/about.md
concepts/strings/links.json

Closes #31 
I noticed another author was on this. He worked on the introduction and links used for reference.

About for the string type concept

---

config.json
exercises/practice/dominoes/src/lib.cairo
exercises/practice/linked-list/.docs/instructions.md
exercises/practice/linked-list/.docs/introduction.md
exercises/practice/linked-list/.meta/config.json
exercises/practice/linked-list/.meta/example.cairo
exercises/practice/linked-list/.meta/tests.toml
exercises/practice/linked-list/Scarb.toml
exercises/practice/linked-list/src/lib.cairo
exercises/practice/linked-list/src/tests.cairo

Add `linked-list` exercise

---

exercises/practice/allergies/src/tests.cairo
exercises/practice/clock/src/tests.cairo
exercises/shared/.docs/help.md
exercises/shared/.docs/tests.md

Add exercise docs

---

config.json
docs/SNIPPET.txt

Add snippet and metadata

---

exercises/practice/scrabble-score/src/lib.cairo

Small typo fix for scrabble-score

Scrable to Scrabble

---

exercises/practice/scrabble-score/.meta/config.json

Added @BNAndras as a contributor to Scrabble

Add BNAndras as contributor to Scrabble

---

concepts/structs/.meta/config.json
concepts/structs/about.md
concepts/structs/introduction.md
concepts/structs/links.json

Closes https://github.com/exercism/cairo/issues/42

structs custom data type

---

config.json
exercises/practice/difference-of-squares/.docs/instructions.md
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/difference-of-squares/.meta/example.cairo
exercises/practice/difference-of-squares/.meta/tests.toml
exercises/practice/difference-of-squares/Scarb.toml
exercises/practice/difference-of-squares/src/lib.cairo
exercises/practice/difference-of-squares/tests/difference_of_squares.cairo

Featured #48in24 exercise from a while back

Add difference-of-squares

---

config.json
exercises/practice/eliuds-eggs/.docs/instructions.md
exercises/practice/eliuds-eggs/.docs/introduction.md
exercises/practice/eliuds-eggs/.meta/config.json
exercises/practice/eliuds-eggs/.meta/example.cairo
exercises/practice/eliuds-eggs/.meta/tests.toml
exercises/practice/eliuds-eggs/Scarb.toml
exercises/practice/eliuds-eggs/src/lib.cairo
exercises/practice/eliuds-eggs/tests/eliuds_eggs.cairo

Another #48in24 exercise but not featured until November-ish.

Add eliuds-eggs

---

config.json
exercises/practice/rotational-cipher/.docs/instructions.md
exercises/practice/rotational-cipher/.meta/config.json
exercises/practice/rotational-cipher/.meta/example.cairo
exercises/practice/rotational-cipher/.meta/tests.toml
exercises/practice/rotational-cipher/Scarb.toml
exercises/practice/rotational-cipher/src/lib.cairo
exercises/practice/rotational-cipher/tests/rotational_cipher.cairo

Another #48in24 exercise from earlier in the year.

Add rotational-cipher

---

config.json
exercises/practice/pangram/.docs/instructions.md
exercises/practice/pangram/.docs/introduction.md
exercises/practice/pangram/.meta/config.json
exercises/practice/pangram/.meta/example.cairo
exercises/practice/pangram/.meta/tests.toml
exercises/practice/pangram/Scarb.toml
exercises/practice/pangram/src/lib.cairo
exercises/practice/pangram/tests/pangram.cairo

Another earlier #48in24 exercise

Add pangram

---

concepts/error-handling/.meta/config.json
concepts/error-handling/about.md
concepts/error-handling/introduction.md
concepts/error-handling/links.json

Added the error-handling concepts along with the examples. Crosschecked the details. Ready to merge.

Error Handling Concept #125 

---

config.json
exercises/practice/matching-brackets/.docs/instructions.md
exercises/practice/matching-brackets/.docs/introduction.md
exercises/practice/matching-brackets/.meta/config.json
exercises/practice/matching-brackets/.meta/example.cairo
exercises/practice/matching-brackets/.meta/tests.toml
exercises/practice/matching-brackets/Scarb.toml
exercises/practice/matching-brackets/src/lib.cairo
exercises/practice/matching-brackets/tests/matching_brackets.cairo

Add matching-brackets

---

config.json
exercises/practice/pascals-triangle/.docs/instructions.md
exercises/practice/pascals-triangle/.docs/introduction.md
exercises/practice/pascals-triangle/.meta/config.json
exercises/practice/pascals-triangle/.meta/example.cairo
exercises/practice/pascals-triangle/.meta/tests.toml
exercises/practice/pascals-triangle/Scarb.toml
exercises/practice/pascals-triangle/src/lib.cairo
exercises/practice/pascals-triangle/tests/pascals_triangle.cairo

This last week's #48in24 exercise

add pascals-triangle

---

config.json
exercises/practice/acronym/.docs/instructions.md
exercises/practice/acronym/.meta/config.json
exercises/practice/acronym/.meta/example.cairo
exercises/practice/acronym/.meta/tests.toml
exercises/practice/acronym/Scarb.toml
exercises/practice/acronym/src/lib.cairo
exercises/practice/acronym/tests/acronym.cairo

Add acronym

---

exercises/practice/bob/.meta/example.cairo

Created this just to check if I'm still [able to merge my own PRs](https://github.com/exercism/cairo/pull/156#issuecomment-2329386778). Seems I'm not.

Remove redundant 'return' statements from bob

---

config.json
exercises/practice/two-fer/.docs/instructions.append.md
exercises/practice/two-fer/.docs/instructions.md
exercises/practice/two-fer/.docs/introduction.md
exercises/practice/two-fer/.meta/config.json
exercises/practice/two-fer/.meta/example.cairo
exercises/practice/two-fer/.meta/tests.toml
exercises/practice/two-fer/Scarb.toml
exercises/practice/two-fer/src/lib.cairo
exercises/practice/two-fer/tests/two_fer.cairo

Towards #246
I didn't end up linking to the Cairo book since https://book.cairo-lang.org/ch06-01-enums.html?highlight=option#the-option-enum-and-its-advantages pretty much gives away how to solve the exercise.

Add two-fer

---

config.json
exercises/concept/annalyns-infiltration/.docs/hints.md
exercises/concept/annalyns-infiltration/.docs/instructions.md
exercises/concept/annalyns-infiltration/.docs/introduction.md
exercises/concept/annalyns-infiltration/.meta/config.json
exercises/concept/annalyns-infiltration/.meta/exemplar.cairo
exercises/concept/annalyns-infiltration/Scarb.toml
exercises/concept/annalyns-infiltration/src/lib.cairo
exercises/concept/annalyns-infiltration/tests/annalyns_infiltration.cairo

Towards #149.
The exemplar file will be shown to mentors during a mentoring discussion for this exercise as an example of a great solution at that point in the syllabus. Therefore, any and all nitpicks are appreciated keeping that in mind.

Add annalyns-infiltration

---

config.json
exercises/practice/triangle/.docs/instructions.md
exercises/practice/triangle/.meta/config.json
exercises/practice/triangle/.meta/example.cairo
exercises/practice/triangle/.meta/tests.toml
exercises/practice/triangle/Scarb.toml
exercises/practice/triangle/src/lib.cairo
exercises/practice/triangle/tests/triangle.cairo

Add triangle

---

config.json
exercises/practice/perfect-numbers/.docs/instructions.md
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/perfect-numbers/.meta/example.cairo
exercises/practice/perfect-numbers/.meta/tests.toml
exercises/practice/perfect-numbers/Scarb.toml
exercises/practice/perfect-numbers/src/lib.cairo
exercises/practice/perfect-numbers/tests/perfect_numbers.cairo

Add perfect-numbers

---

config.json
exercises/practice/nucleotide-count/.docs/instructions.md
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/nucleotide-count/.meta/example.cairo
exercises/practice/nucleotide-count/.meta/tests.toml
exercises/practice/nucleotide-count/Scarb.toml
exercises/practice/nucleotide-count/src/lib.cairo
exercises/practice/nucleotide-count/tests/nucleotide_count.cairo

Add nucleotide-count

---

bin/verify-exercises

Towards https://github.com/exercism/cairo/issues/276

Add timeout to _./bin/verify-exercises_

---

config.json
exercises/practice/proverb/.docs/instructions.md
exercises/practice/proverb/.meta/config.json
exercises/practice/proverb/.meta/example.cairo
exercises/practice/proverb/.meta/tests.toml
exercises/practice/proverb/Scarb.toml
exercises/practice/proverb/src/lib.cairo
exercises/practice/proverb/tests/proverb.cairo

Add `proverb`

---

config.json
exercises/practice/grains/.docs/instructions.md
exercises/practice/grains/.meta/config.json
exercises/practice/grains/.meta/example.cairo
exercises/practice/grains/.meta/tests.toml
exercises/practice/grains/Scarb.toml
exercises/practice/grains/src/lib.cairo
exercises/practice/grains/tests/grains.cairo

Implement `grains`

---

config.json
exercises/practice/minesweeper/.docs/instructions.md
exercises/practice/minesweeper/.docs/introduction.md
exercises/practice/minesweeper/.meta/config.json
exercises/practice/minesweeper/.meta/example.cairo
exercises/practice/minesweeper/.meta/tests.toml
exercises/practice/minesweeper/Scarb.toml
exercises/practice/minesweeper/src/lib.cairo
exercises/practice/minesweeper/tests/minesweeper.cairo

Add `minesweeper` exercise

---

config.json
exercises/practice/space-age/.docs/hints.md
exercises/practice/space-age/.docs/instructions.append.md
exercises/practice/space-age/.docs/instructions.md
exercises/practice/space-age/.docs/introduction.md
exercises/practice/space-age/.meta/config.json
exercises/practice/space-age/.meta/example.cairo
exercises/practice/space-age/.meta/tests.toml
exercises/practice/space-age/Scarb.toml
exercises/practice/space-age/src/lib.cairo
exercises/practice/space-age/tests/space_age.cairo
go.work

Add `space-age` exercise

---

config.json
exercises/practice/luhn/.docs/instructions.md
exercises/practice/luhn/.meta/config.json
exercises/practice/luhn/.meta/example.cairo
exercises/practice/luhn/.meta/tests.toml
exercises/practice/luhn/Scarb.toml
exercises/practice/luhn/src/lib.cairo
exercises/practice/luhn/tests/luhn.cairo

Add `luhn` exercise

---

config.json
exercises/practice/knapsack/.docs/instructions.md
exercises/practice/knapsack/.docs/introduction.md
exercises/practice/knapsack/.meta/config.json
exercises/practice/knapsack/.meta/example.cairo
exercises/practice/knapsack/.meta/tests.toml
exercises/practice/knapsack/Scarb.toml
exercises/practice/knapsack/src/lib.cairo
exercises/practice/knapsack/tests/knapsack.cairo

Add knapsack

---

config.json
exercises/practice/resistor-color/.docs/instructions.md
exercises/practice/resistor-color/.meta/config.json
exercises/practice/resistor-color/.meta/example.cairo
exercises/practice/resistor-color/.meta/tests.toml
exercises/practice/resistor-color/Scarb.toml
exercises/practice/resistor-color/src/lib.cairo
exercises/practice/resistor-color/tests/resistor_color.cairo

Add `resistor-color`

---

config.json
exercises/practice/etl/.docs/instructions.append.md
exercises/practice/etl/.docs/instructions.md
exercises/practice/etl/.docs/introduction.md
exercises/practice/etl/.meta/config.json
exercises/practice/etl/.meta/example.cairo
exercises/practice/etl/.meta/tests.toml
exercises/practice/etl/Scarb.toml
exercises/practice/etl/src/lib.cairo
exercises/practice/etl/tests/etl.cairo

 Add Practice Exercise: `etl`

---

concepts/type-conversion/.meta/config.json
concepts/type-conversion/about.md
concepts/type-conversion/introduction.md
concepts/type-conversion/links.json

implement type-conversion concept

---

concepts/operator-overloading/.meta/config.json
concepts/operator-overloading/about.md
concepts/operator-overloading/introduction.md
concepts/operator-overloading/links.json

implement operator overloading concept

---

concepts/arrays/links.json
concepts/dictionaries/.meta/config.json
concepts/dictionaries/about.md
concepts/dictionaries/introduction.md
concepts/dictionaries/links.json

Write the "Dictionaries" concept

---

exercises/concept/chrono-realms/.docs/hints.md
exercises/concept/chrono-realms/.docs/instructions.md
exercises/concept/chrono-realms/.docs/introduction.md
exercises/concept/chrono-realms/.meta/config.json
exercises/concept/chrono-realms/.meta/design.md

Add Concept Exercise Metadata Files: chrono-realms

---

exercises/concept/cryptographer/.docs/instructions.md
exercises/concept/cryptographer/.meta/config.json
exercises/concept/cryptographer/.meta/exemplar.cairo
exercises/concept/cryptographer/Scarb.toml
exercises/concept/cryptographer/src/lib.cairo
exercises/concept/cryptographer/tests/cryptographer.cairo

Add concept exercise: `cryptographer`

---

concepts/ownership/about.md
exercises/concept/election-day/.docs/hints.md
exercises/concept/election-day/.docs/instructions.md
exercises/concept/election-day/.docs/introduction.md
exercises/concept/election-day/.meta/config.json
exercises/concept/election-day/.meta/design.md
exercises/concept/election-day/.meta/exemplar.cairo
exercises/concept/election-day/Scarb.toml
exercises/concept/election-day/src/lib.cairo
exercises/concept/election-day/tests/election_day.cairo

Add Concept Exercise: election-day

---

.github/workflows/lint.yml
.github/workflows/test.yml

http://forum.exercism.org/t/github-actions-runner-breaking-changes-announced/12612/10

ci uses ubuntu-24.04

---

config.json
exercises/concept/election-day/.meta/design.md
exercises/concept/health-statistics/.meta/config.json
exercises/concept/health-statistics/.meta/design.md
exercises/concept/health-statistics/.meta/exemplar.cairo
exercises/concept/health-statistics/Scarb.toml
exercises/concept/health-statistics/src/lib.cairo
exercises/concept/health-statistics/tests/health_statistics.cairo

Add Concept Exercise: `health-statistics`

---

exercises/concept/election-day/tests/election_day.cairo

Fixes https://github.com/exercism/cairo/actions/runs/16714927871/job/47306509129

Ignore last election-day test

---

exercises/concept/airport-robot/.docs/instructions.md
exercises/concept/airport-robot/.docs/introduction.md
exercises/concept/airport-robot/.meta/config.json
exercises/concept/airport-robot/.meta/design.md
exercises/concept/airport-robot/.meta/exemplar.cairo
exercises/concept/airport-robot/Scarb.toml
exercises/concept/airport-robot/src/lib.cairo
exercises/concept/airport-robot/tests/airport_robot.cairo

Add Concept Exercise: `airport-robot`

---

exercises/practice/binary-search-tree/tests/binary_search_tree.cairo

Addresses failing CI https://github.com/exercism/cairo/actions/runs/16715194540/job/47307204857

update binary_search_tree: ignore non-1st tests

---

bin/verify-exercises
exercises/concept/airport-robot/src/lib.cairo
exercises/concept/bakery-order-system/.meta/config.json
exercises/concept/bakery-order-system/.meta/exemplar.cairo
exercises/concept/bakery-order-system/src/lib.cairo
exercises/concept/chrono-realms/.meta/config.json
exercises/concept/chrono-realms/src/lib.cairo
exercises/concept/election-day/.meta/exemplar.cairo
exercises/concept/health-statistics/src/lib.cairo
exercises/concept/magical-measurements/.meta/exemplar.cairo
exercises/concept/weather-report/.meta/exemplar.cairo
exercises/concept/weather-report/src/lib.cairo

Lighten/harden the difficulty of concept exercises to make them more interesting or simply more appropriate for students.
Concept relations based on PR #380

Refactor Exercises Based on which Concepts the Student is already Familiar with
